### ISSUE TITLE
KeyError when using design_byseq method

### ISSUE THREAD

**Issue by polymerase60053** [JoreyYan/zetadesign#1]
Hello, I'm trying to use your excellent work to put ProteinMPNN designed sequence onto its backbone. As you said in the README, I passed `name` and `seq` to `design_byseq`, but it returns the error below: 
```
Traceback (most recent call last):
  File "/pubhome/hjhe/software/zetadesign/Joint_to_repacker.py", line 714, in <module>
    args.design_byseq(None, argss.seq)
  File "/pubhome/hjhe/software/zetadesign/Joint_to_repacker.py", line 637, in design_byseq
    self.design_step_byseq(name, aatype)
  File "/pubhome/hjhe/software/zetadesign/Joint_to_repacker.py", line 461, in design_step_byseq
    losses.update([result['bfloss'].item(), result['ca_loss'].item(), result['chi_loss'].item(),
KeyError: 'ca_loss'
```
I compared the corresponding `losses.update(...` sentence in the `design_step` method, and I'm wondering whether `'ca_loss'` should be `'fapeloss'`? 

By the way, I think the 3rd sentence in `design_byseq` method should be `self.load_module(True)`.

**Comment by JoreyYan** [comment]
sorry， design by seq module had not been update. but you are right, it should be fapeloss. 
the 3rd sentence in design_byseq method could be self.load_module(True) or self.load_module( use_J)
